language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
# install:
#   - pip install
# which branch to build
# branches:
#   only:
#     - sudoku_solver_hard
# command to run tests
script: 
  - pytest ./kyu4/Python/src/test*.py  -v --cov=. --cov-report term-missing

